baseURL: https://serbia70.com
languageCode: zh-cn # en-us
title: å¡å›½007
theme: PaperMod  # ä¸»é¢˜åå­—ï¼Œå’Œthemesæ–‡ä»¶å¤¹ä¸‹çš„ä¸€è‡´

enableInlineShortcodes: true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true

hasCJKLanguage: false # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics:  # è°·æ­Œç»Ÿè®¡
# Copyright: Sulv

paginate: 15    # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
summaryLength: 140 # æ–‡ç« æ¦‚è§ˆçš„å­—æ•°ï¼Œé»˜è®¤70

minify:
  disableXML: true
  # minifyOutput: true

permalinks: # è®¿é—®åšå®¢æ—¶ç½‘å€çš„æ˜¾ç¤ºå½¢å¼
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: en # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
defaultContentLanguageInSubdir: false

languages:
  
  en:  
    #languageName: "English"
   
    # profileMode:
    #   enabled: true
    #   title: (=^ï½¥Ï‰ï½¥^=)
    #   subtitle: ğŸ‘‡ æ¬¢è¿å…‰ä¸´å°ç«™ï¼Œè”ç³»æ–¹å¼ ğŸ‘‡
    #   # subtitle: "ğŸ§¨å­¦è€Œæ—¶ä¹ ä¹‹ï¼Œä¸äº¦è¯´ä¹ï¼Ÿæœ‰æœ‹è‡ªè¿œæ–¹æ¥ï¼Œä¸äº¦ä¹ä¹ï¼Ÿ<br/>ğŸ‘‡è”ç³»æ–¹å¼"
    #   imageUrl: "img/avatar.gif"
    #   imageTitle: 
    #   imageWidth: 120
    #   imageHeight: 120
    #   buttons:
    #     - name: ğŸ‘¨ğŸ»â€ğŸ’» æŠ€æœ¯
    #       url: posts/tech
    #     - name: ğŸ—ï¸ å»ºç«™
    #       url: posts/blog
    #     - name: ğŸ“– é˜…è¯»
    #       url: posts/read
    #     - name: ğŸ–ï¸ ç”Ÿæ´»
    #       url: posts/life
    params: 
      homeInfoParams:
        Title: "æ¬¢è¿æ¥åˆ°å¡å›½007åäººä¿¡æ¯ç½‘"
        Content: >
          æœ¬ç«™ä¸»è¦åŒ…æ‹¬å¡å°”ç»´äºšç§»æ°‘ä¹°æˆ¿ã€è¯»ä¹¦ã€ç”Ÿæ´»ç­‰ç›¸å…³èµ„è®¯ã€‚</br>                  
          é‡åˆ°ä¸æ‡‚çš„åœ°æ–¹å¯ä»¥åŠ æˆ‘å¾®ä¿¡å’¨è¯¢ï¼šserbia70 </br> 
          å»ºè®®æ”¶è— <a href="/web" target="_blank"><font color="#FF0000"><strong>å¡å°”ç»´äºšç½‘å€å¯¼èˆª</strong></font></a>  
          
          å¸Œæœ›èƒ½ç»™å¤§å®¶çš„ç§»æ°‘ç”Ÿæ´»å¸¦æ¥ä¸€ç‚¹ç‚¹ä¾¿åˆ© </br> 
          
        

    menu:
      main:
        - identifier: home
          name: ä¸»é¡µ
          url: /
          weight: 10
        - identifier: search
          name:  æœç´¢
          url: search
          weight: 20
        - identifier: ç§»æ°‘
          name: ç§»æ°‘
          url: tags/ç§»æ°‘/
          weight: 30 
        - identifier: ç”Ÿæ´»
          name: ç”Ÿæ´»
          url: tags/ç”Ÿæ´»/
          weight: 40 
        - identifier: æˆ¿äº§
          name: æˆ¿äº§
          url: tags/æˆ¿äº§/
          weight: 50      
        - identifier: å­¦æ ¡
          name: å­¦æ ¡
          url: tags/å­¦æ ¡/
          weight: 60 
        - identifier: guanggao
          name: ç½‘å€å¯¼èˆª
          url: /web
          weight: 70            
     
        #  - identifier: links
          #  name:  å‹é“¾
          #  url: links
          #  weight: 40
        #  - identifier: about2
          #  name: æ²¡æœ‰
          #  url: tags/shell/
          #  weight: 50
        #  - identifier: categories
          #  name: ç”Ÿæ´»
          #  url: categories
          #  weight: 60
        #  - identifier: categories2
          #  name: é»„é¡µ
          #  url: categories2
          #  weight: 70
        #  - identifier: categories3
          #  name: å¹¿å‘Š
          #  url: categories3
          #  weight: 80
       

outputs:
  home:
    - HTML
    - RSS
    - JSON

# è¿™é‡Œçš„å‚æ•°ä¼šè¢«ä»£ç ä»¥ .Site.Params çš„å½¢å¼è¯»å–
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "å¡å°”ç»´äºšä¹‹å®¶, å¡å°”ç»´äºšç§»æ°‘, å¡å°”ç»´äºšç”Ÿæ´», å¡å°”ç»´äºšæˆ¿äº§, å¡å°”ç»´äºšå­¦æ ¡,å¡å°”ç»´äºšä¹°æˆ¿,å¡å›½007,"
  author: ité™ˆ # author: ["Me", "You"] # multiple authors
  draft: flase
  defaultTheme: auto  # defaultTheme: light or  dark 
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  disableShare: true 
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # éšè—é¡µè„š
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´

  ShowToc: true # æ˜¾ç¤ºç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  comments: true # æ˜¯å¦å¼€å¯è¯„è®º
  
  extendCodeBackground: false # ä»£ç å—æ˜¯å¦æ¨ªå‘å±•å¼€

  socialIcons:
    
    - name: WeChat
      url: "img/wechat.png"
    - name: xiaohongshu
      url: "https://www.xiaohongshu.com/user/profile/62c99f18000000000303d6f8"
    - name: bilibili
      url: "https://space.bilibili.com/405346207"
    - name: RSS
      url: "index.xml"

  label:
    text: "å¡å°”ç»´äºšä¹‹å®¶"
    icon: "img/avatar.gif"
    iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: ""

  assets:
    favicon: "img/avatar.gif"
    favicon16x16: "img/avatar.gif"
    favicon32x32: "img/avatar.gif"
    apple_touch_icon: "img/avatar.gif"
    safari_pinned_tab: "img/avatar.gif"

  cover:
    hidden: false          # éšè—coverå›¾ç‰‡ï¼Œä½†æ˜¯ä¸åœ¨æ ¼å¼åŒ–æ•°æ®ä¸­éšè—
    hiddenInList: false   # åœ¨åˆ—è¡¨é¡µéšè—coverå›¾ç‰‡
    hiddenInSingle: true  # åœ¨æ–‡ç« å†…å®¹é¡µéšè—coverå›¾ç‰‡

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary"]

  # footeré…ç½®
  StartYear: 2024 # åº•éƒ¨å¼€å§‹å¹´ä»½
  FilingNo: äº¬ICPå¤‡2021023168å·-1 # åº•éƒ¨å¤‡æ¡ˆå·
  # PublicSecurityIconLink: å¡«è‡ªå·±çš„å…¬å®‰å›¾æ ‡é“¾æ¥ # å¡«è‡ªå·±çš„å…¬å®‰å›¾æ ‡é“¾æ¥,å¯ç”¨ç»å¯¹è·¯å¾„ï¼Œç›¸å¯¹è·¯å¾„å¦‚ img/beian.png
  # PublicNetworkSecurity: å¡«è‡ªå·±çš„å…¬ç½‘å®‰å¤‡ # åº•éƒ¨å…¬ç½‘å®‰å¤‡å·

  # æ‰“èµ
  Reward: false 
  # å¯ç”¨ç»å¯¹å’Œç›¸å¯¹åœ°å€ï¼Œç›¸å¯¹åœ°å€çš„å›¾ç‰‡éœ€æ”¾åœ¨static/imgä¸‹
  WechatPay: img/wechat_pay.png
  Alipay: img/alipay.png #æ‰“èµæ”¯ä»˜å®å›¾ç‰‡åœ°å€

  # twkiooè¯„è®º
  twikoo:
    version: 1.6.35

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯
  highlight:
    codeFences: true   # ä»£ç å›´æ åŠŸèƒ½ï¼Œè¿™ä¸ªåŠŸèƒ½ä¸€èˆ¬éƒ½è¦è®¾ä¸º true çš„ï¼Œä¸ç„¶å¾ˆéš¾çœ‹ï¼Œå°±æ˜¯å¹²å·´å·´çš„-ä»£ç æ–‡å­—ï¼Œæ²¡æœ‰é¢œè‰²ã€‚
    guessSyntax: true # çŒœæµ‹è¯­æ³•ï¼Œè¿™ä¸ªåŠŸèƒ½å»ºè®®è®¾ç½®ä¸º true, å¦‚æœä½ æ²¡æœ‰è®¾ç½®è¦æ˜¾ç¤ºçš„è¯­è¨€åˆ™ä¼šè‡ªåŠ¨åŒ¹é…ã€‚
    lineNos: false     # æ˜¯å¦æ˜¾ç¤ºè¡Œå·
    noClasses: true    # ä½¿ç”¨ class æ ‡ç­¾ï¼Œè€Œä¸æ˜¯å†…åµŒçš„å†…è”æ ·å¼
    tabWidth: 4
    style: paraiso-dark
    # anchorLineNos: true
    # hl_Linesï¼šé«˜äº®çš„è¡Œå·ï¼Œä¸€èˆ¬è¿™ä¸ªä¸è®¾ç½®ï¼Œå› ä¸ºæ¯ä¸ªä»£ç å—æˆ‘ä»¬å¯èƒ½å¸Œæœ›è®©é«˜äº®çš„åœ°æ–¹ä¸ä¸€æ ·ã€‚
    # lineNoStartï¼šè¡Œå·ä»ç¼–å·å‡ å¼€å§‹ï¼Œä¸€èˆ¬ä» 1 å¼€å§‹ã€‚
    # lineNumbersInTableï¼šä½¿ç”¨è¡¨æ¥æ ¼å¼åŒ–è¡Œå·å’Œä»£ç ,è€Œä¸æ˜¯ æ ‡ç­¾ã€‚è¿™ä¸ªå±æ€§ä¸€èˆ¬è®¾ç½®ä¸º true.

privacy:
  vimeo:
    disabled: false
    simple: true
  
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  
  instagram:
    disabled: false
    simple: true
  
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
        
